application: snippets-dev
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /_ah/mail/snippets@.*snippets-dev\.appspotmail\.com 
  script: receive_email.py
  login: admin

- url: .*
  script: main.py
  secure: always
    
inbound_services:
- mail